import type {
  IngredientsListRequest,
  IngredientsListResponse,
  IngredientCreateRequest,
  IngredientCreateResponse,
  IngredientUpdateRequest,
  IngredientDeleteRequest,
  UnitsListRequest,
  UnitsListResponse,
  CategoriesListRequest,
  CategoriesListResponse,
  CategoryCreateRequest,
  CategoryCreateResponse,
  CategoryUpdateRequest,
  CategoryDeleteRequest,
  RecipesListRequest,
  RecipesListResponse,
  RecipesGetRequest,
  RecipesGetResponse,
  RecipesCreateRequest,
  RecipesCreateResponse,
  RecipesUpdateRequest,
  RecipesDeleteRequest,
  RecipeIngredientsSetRequest,
} from '../../shared/ipc'

export const api = {
  ingredients: {
    list: (req?: IngredientsListRequest) => window.api.ingredients.list(req) as Promise<IngredientsListResponse>,
    create: (req: IngredientCreateRequest) => window.api.ingredients.create(req) as Promise<IngredientCreateResponse>,
    update: (req: IngredientUpdateRequest) => window.api.ingredients.update(req) as Promise<{ ok: true }>,
    delete: (req: IngredientDeleteRequest) => window.api.ingredients.delete(req) as Promise<{ ok: true }>,
  },
  units: {
    list: (req?: UnitsListRequest) => window.api.units.list(req) as Promise<UnitsListResponse>,
  },
  categories: {
    list: (req?: CategoriesListRequest) => window.api.categories.list(req) as Promise<CategoriesListResponse>,
    create: (req: CategoryCreateRequest) => window.api.categories.create(req) as Promise<CategoryCreateResponse>,
    update: (req: CategoryUpdateRequest) => window.api.categories.update(req) as Promise<{ ok: true }>,
    delete: (req: CategoryDeleteRequest) => window.api.categories.delete(req) as Promise<{ ok: true }>,
  },
  recipes: {
    list: (req?: RecipesListRequest) => window.api.recipes.list(req) as Promise<RecipesListResponse>,
    get: (req: RecipesGetRequest) => window.api.recipes.get(req) as Promise<RecipesGetResponse>,
    create: (req: RecipesCreateRequest) => window.api.recipes.create(req) as Promise<RecipesCreateResponse>,
    update: (req: RecipesUpdateRequest) => window.api.recipes.update(req) as Promise<{ ok: true }>,
    delete: (req: RecipesDeleteRequest) => window.api.recipes.delete(req) as Promise<{ ok: true }>,
    setIngredients: (req: RecipeIngredientsSetRequest) => window.api.recipes.setIngredients(req) as Promise<{ ok: true }>,
  },
} as const
